### ISSUE TITLE
How to connect Android Docker emulator in jenkins pipeline script?

### ISSUE THREAD

**Issue by selvakumar1994** [vgaidarji/ci-matters#22]
currently i working in Jenkins for android continuous integration and continuous Deploy.now i struggling in Android instrumentation testing.anyone give me the solution..

**Comment by vgaidarji** [comment]
@selvakumar1994 Hey. Are you using some setup from the current repository and something is not working? This repo has no info on how to `How to connect Android Docker emulator in jenkins pipeline script`. Sorry, but it seems to me more like a StackOverflow question.
