### ISSUE TITLE
Integrate project with Circle CI

### ISSUE THREAD

**Issue by vgaidarji** [vgaidarji/ci-matters#8]
Ideally, no changes should be made to project structure.
See integration with other CI's (markdown files) to understand requirements.
Scripts for emulator already exists in the project and should be reused if possible.

**Comment by iamabel** [comment]
I can take this one too!

**Comment by cpanato** [comment]
I will take this one 🎉

**Comment by vgaidarji** [comment]
@cpanato nice! 🚀 Please refer to [comment](https://github.com/vgaidarji/ci-matters/issues/6#issuecomment-333047318) if you need more context.

**Comment by vgaidarji** [comment]
@cpanato  You might need the following information for full setup
![image](https://user-images.githubusercontent.com/3036347/31018010-316c6360-a533-11e7-8ea1-6857f8b2c556.png)
Please contact me via email (check my Github account) and we can find a way to fill that information.
